// plugins/react/HireSortJobs.tsx
import React, { useEffect, useRef, useState } from 'react';

export interface HireSortJobsProps {
  /**
   * Your unique company slug in HireSort (e.g. 'zool').
   */
  clientSlug?: string;

  /**
   * Theme mode: 'dark' or 'light'. Defaults to 'dark'.
   */
  theme?: 'dark' | 'light';

  /**
   * Base URL of the HireSort ATS instance.
   * Defaults to 'http://localhost:8080' in development or 'https://app.hiresort.ai' in production.
   */
  atsBaseUrl?: string;

  /**
   * Optional custom CSS class name for the wrapper div.
   */
  className?: string;

  /**
   * Initial minimum height in pixels before content loads. Defaults to 600.
   */
  initialHeight?: number;
}

export const HireSortJobs: React.FC<HireSortJobsProps> = ({
  clientSlug = 'zool',
  theme = 'dark',
  atsBaseUrl = typeof window !== 'undefined' && window.location.hostname === 'localhost'
    ? 'http://localhost:8080'
    : 'https://app.hiresort.ai',
  className = '',
  initialHeight = 650,
}) => {
  const iframeRef = useRef<HTMLIFrameElement>(null);
  const [iframeHeight, setIframeHeight] = useState<number>(initialHeight);
  const [isLoading, setIsLoading] = useState<boolean>(true);

  useEffect(() => {
    const handleMessage = (event: MessageEvent) => {
      // Validate event type
      if (!event.data || event.data.type !== 'HIRESORT_RESIZE') {
        return;
      }

      // Check clientSlug match if provided
      if (event.data.clientSlug && event.data.clientSlug !== clientSlug) {
        return;
      }

      if (typeof event.data.height === 'number' && event.data.height > 100) {
        setIframeHeight(event.data.height);
        setIsLoading(false);
      }
    };

    window.addEventListener('message', handleMessage);
    return () => window.removeEventListener('message', handleMessage);
  }, [clientSlug]);

  const embedUrl = `${atsBaseUrl.replace(/\/$/, '')}/embed/careers/${encodeURIComponent(clientSlug)}?theme=${encodeURIComponent(theme)}`;

  return (
    <div 
      className={`hiresort-embed-wrapper relative w-full transition-all duration-300 ${className}`}
      style={{ minHeight: `${iframeHeight}px` }}
    >
      {isLoading && (
        <div className="absolute inset-0 flex items-center justify-center bg-background/50 backdrop-blur-sm z-10">
          <div className="flex items-center gap-3 text-sm text-muted-foreground animate-pulse">
            <div className="w-4 h-4 rounded-full border-2 border-primary border-t-transparent animate-spin" />
            Loading career opportunities...
          </div>
        </div>
      )}

      <iframe
        ref={iframeRef}
        src={embedUrl}
        id={`hiresort-iframe-${clientSlug}`}
        title={`HireSort Careers Portal — ${clientSlug}`}
        className="w-full border-0 rounded-xl overflow-hidden block transition-all duration-200"
        style={{
          height: `${iframeHeight}px`,
          backgroundColor: theme === 'dark' ? '#0b0f19' : '#ffffff',
        }}
        onLoad={() => setIsLoading(false)}
        loading="lazy"
      />
    </div>
  );
};

export default HireSortJobs;

// plugins/web-component/hiresort-jobs.js
/**
 * HireSort AI — Custom Web Component (<hiresort-jobs>)
 * Version: 1.0.0
 * 
 * Usage:
 *   <script type="module" src="https://app.hiresort.ai/plugins/web-component/hiresort-jobs.js"></script>
 *   <hiresort-jobs client="zool" theme="dark"></hiresort-jobs>
 */

class HireSortJobsElement extends HTMLElement {
  static get observedAttributes() {
    return ['client', 'theme', 'ats-url'];
  }

  constructor() {
    super();
    this.attachShadow({ mode: 'open' });
    this.iframe = document.createElement('iframe');
    this.onResizeMessage = this.onResizeMessage.bind(this);
  }

  connectedCallback() {
    this.render();
    window.addEventListener('message', this.onResizeMessage);
  }

  disconnectedCallback() {
    window.removeEventListener('message', this.onResizeMessage);
  }

  attributeChangedCallback(name, oldValue, newValue) {
    if (oldValue !== newValue) {
      this.render();
    }
  }

  onResizeMessage(event) {
    if (!event.data || event.data.type !== 'HIRESORT_RESIZE') return;
    const client = this.getAttribute('client') || 'default';
    if (event.data.clientSlug && event.data.clientSlug !== client) return;

    if (typeof event.data.height === 'number' && event.data.height > 100) {
      this.iframe.style.height = event.data.height + 'px';
    }
  }

  render() {
    const client = this.getAttribute('client') || 'default';
    const theme = this.getAttribute('theme') || 'dark';
    const atsUrl = this.getAttribute('ats-url') || (
      window.location.hostname === 'localhost' ? 'http://localhost:8080' : 'https://app.hiresort.ai'
    );

    const embedUrl = `${atsUrl.replace(/\/$/, '')}/embed/careers/${encodeURIComponent(client)}?theme=${encodeURIComponent(theme)}`;

    this.shadowRoot.innerHTML = `
      <style>
        :host {
          display: block;
          width: 100%;
          max-width: 100%;
          font-family: system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
        }
        iframe {
          width: 100%;
          height: 650px;
          min-height: 500px;
          border: none;
          display: block;
          border-radius: 12px;
          overflow: hidden;
          background-color: ${theme === 'dark' ? '#0b0f19' : '#ffffff'};
          transition: height 0.25s ease;
        }
      </style>
    `;

    this.iframe.src = embedUrl;
    this.iframe.title = `HireSort Careers — ${client}`;
    this.shadowRoot.appendChild(this.iframe);
  }
}

if (!customElements.get('hiresort-jobs')) {
  customElements.define('hiresort-jobs', HireSortJobsElement);
}

export default HireSortJobsElement;
